### ISSUE TITLE
Doesn't have color after calibration 

### ISSUE THREAD

**Issue by djsmartboy** [thomwolf/GreatSand#61]
Hello,

I having some trouble with the software
after i have calibrate the kinect and the beamer
i start the game the welcome screen will appear nicely in color
but after that i don't have any color or image on the sandbox

**Comment by djsmartboy** [comment]
Anybody?

**Comment by zzzeddy** [comment]
I have exactly same problem. I need help!

Platform 
- Windows 7, 10
- Kinect for Windows v1 (with recommended usb driver at tutorial)
- Magic-Sand S/W (latest)

Symptom
- Calibration is successfully done but no image on sand
- pressing spacebar , game starts with welcome image but not with contour images

**Comment by KondakovArtem** [comment]
Hi, I seem to have the same problem. And there is a suspicion that the problem is in the shaders. Calibration is successful, the game starts, fish appear, but there is no height map.

At the same time, shader compilation errors appear in the application console
I tried replacing shadersGL2 with shadersGL3, errors disappeared, but the height map did not appear

Please tell me, maybe there are ideas what could be the problem


Number of screens found: 2
Monitor 0 size: 1680x1050
Number of screens found: 2
Monitor 1 size: 1680x1050
read 9 reference maps
ofxSmartFont :: new font added : modal-title @ pt size 24
ofxSmartFont :: new font added : modal-message @ pt size 20
ofxSmartFont :: new font added : modal-title @ pt size 20
ofxSmartFont :: new font added : modal-message @ pt size 16
ofxSmartFont :: new font added : Verdana.ttf @ pt size 6
libusb-win32: dll version 1.2.6.0 | driver (libusb0.sys) version 1.2.6.0
libusb-win32: dll version 1.2.6.0 | driver (libusb0.sys) version 1.2.6.0
[verbose] KinectProjector: KinectProjector.setup(): kinectROI 0, 0, 0, 640, 480
[verbose] kinectGrabber: setupFramefilter(): Gradient Field resolution: 10
[verbose] kinectGrabber: setupFramefilter(): Width: 640 Gradient Field Cols: 64
[verbose] kinectGrabber: setupFramefilter(): Height: 480 Gradient Field Rows: 48

[verbose] kinectGrabber: getWorldMatrix(): Computing kinect world matrix
[verbose] KinectProjector: KinectProjector.setup(): kinectWorldMatrix: 0.0017366
4,        0,        0, -0.555733
       0, 0.00173667,        0,  -0.4168
       0,        0,        0,        1
       0,        0,        0,        1
Thread execution started.
ReapThreadProc(): no pending transfers, sleeping until delivery...
[ERROR] :: Component Not Found : test
[verbose] SandSurfaceRenderer: SandSurfaceRenderer.setup(): sandSurfaceRendererS
ettings.xml loaded
[verbose]       HeightColorMap.xml
[verbose]       Sandy.xml
[verbose]       test.xml
[verbose] listed 3 files in "colorMaps/\"
[verbose] SandSurfaceRenderer: setupMesh. KinectROI: 0, 0, 0, 640, 480
Thread execution started.
ReapThreadProc(): no pending transfers, sleeping until delivery...
[verbose] SandSurfaceRenderer: setup(): Loading shadersGL2/elevationShader
1760 remaining out of 5280
1920 remaining out of 46080
316 remaining out of 19540
[ error ] ofShader: setupShaderFromSource(): GL_VERTEX_SHADER shader failed to c
ompile
[ error ] ofShader: GL_VERTEX_SHADER shader reports:
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(46) : error C7531: global function texture2DRect requires "#extension GL_ARB_t
exture_rectangle : enable" before use

[ error ] ofShader: GL_VERTEX_SHADER, offending line 29 :
           27   varying float depthfrag;
           28
           29   uniform sampler2DRect tex0; // Sampler for the depth image-space
 elevation texture
           30   uniform vec2 depthTransformation; // Normalisation factor and of
fset applied by openframeworks
           31   uniform vec2 contourLineFboTransformation; // Transformation fro
m elevation to normalized contourline fbo unit factor and offset

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
Vertex info
-----------
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(46) : error C7531: global function texture2DRect requires "#extension GL_ARB_t
exture_rectangle : enable" before use

[verbose] SandSurfaceRenderer: setup(): Loading shadersGL2/heightMapShader
[ error ] ofShader: setupShaderFromSource(): GL_VERTEX_SHADER shader failed to c
ompile
[ error ] ofShader: GL_VERTEX_SHADER shader reports:
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(45) : error C7531: global function texture2DRect requires "#extension GL_ARB_t
exture_rectangle : enable" before use

1920 remaining out of 36480
[ error ] ofShader: GL_VERTEX_SHADER, offending line 29 :
           27   varying float depthfrag;
           28
           29   uniform sampler2DRect tex0; // Sampler for the depth image-space
 elevation texture automatically set by binding
           30
           31   uniform mat4 kinectProjMatrix; // Transformation from kinect wor
ld space to proj image space

448 remaining out of 33112
[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to
 compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(37) : error C7531: global function texture2DRect requires "#e1760 remaining ou
t of 31680
xtension GL_ARB_texture_rectangle : enable" before use

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 29 :
           27   varying float depthfrag;
           28
           29   uniform sampler2DRect heightColorMapSampler;
           30   uniform sampler2DRect pixelCornerElevationSampler; // Sampler fo
r the half pixel texture
           31   uniform float contourLineFactor;

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
Vertex info
-----------
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(45) : error C7531: global function texture2DRect requires "#extension GL_ARB_t
exture_rectangle : enable" before use

Fragment info
-------------
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(37) : error C7531: global function texture2DRect requires "#extension GL_ARB_t
exture_rectangle : enable" before use

[verbose] SandSurfaceRenderer: setRangesAndBasePlaneEquation(): basePlaneOffset:
 0, 0, 870
[verbose] SandSurfaceRenderer: setRangesAndBasePlaneEquation(): basePlaneNormal:
 0, 0, 1
read 9 reference maps
[ error ] ofXml: couldn't load, "BornholmOversigt3_scores.xml" not found
Could not read bin\data\mapGame/Scores/BornholmOversigt3_scores.xml
[ error ] ofXml: couldn't load, "AeroeOversigt_scores.xml" not found
Could not read bin\data\mapGame/Scores/AeroeOversigt_scores.xml
[ error ] ofXml: couldn't load, "AustraliaOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/AustraliaOnly_scores.xml
[ error ] ofXml: couldn't load, "GreenlandOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/GreenlandOnly_scores.xml
[ error ] ofXml: couldn't load, "UKOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/UKOnly_scores.xml
[ error ] ofXml: couldn't load, "SicilyOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/SicilyOnly_scores.xml
[ error ] ofXml: couldn't load, "IcelandOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/IcelandOnly_scores.xml
[ error ] ofXml: couldn't load, "MadagascarOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/MadagascarOnly_scores.xml
[ error ] ofXml: couldn't load, "CreteOnly_scores.xml" not found
Could not read bin\data\mapGame/Scores/CreteOnly_scores.xml
CTemporalFrameFilter::NewFrame: No color buffer allocated: allocating
1920 remaining out of 28800
3520 remaining out of 19360
1812 remaining out of 3756
1760 remaining out of 12320
1760 remaining out of 8800
1920 remaining out of 42240
892 remaining out of 6676
1920 remaining out of 5760
1920 remaining out of 5760
692 remaining out of 12236

**Comment by KondakovArtem** [comment]
After 2 weeks of research, I solved the problem by installing a clean Window 7 + Visual C ++ run-time components distribution. Apparently some later versions of VC run time or something else that resulted in an error were installed.

I also managed to build an application for Linux Ubuntu, but only on version 14.04, because it uses gcc 4 version, which is suitable for openframeworks 0.9.3

**Comment by kreosz** [comment]
Hi.
What versions of Visual C ++ do you have installed on Windows 7? I am struggling with the same problem.

**Comment by KondakovArtem** [comment]
Hi
Now i have this installed
![image](https://user-images.githubusercontent.com/12134542/97215103-17d15600-17d5-11eb-86ea-4d4f2beda0ab.png)
I think 2015-2019 is enouth, but it is not exactly

**Comment by RasmusRPaulsen** [comment]
It seems that the graphics card or the graphic drivers does not support OpenGL Shading Language version 1.4 (#version 140) which is required to compile the shaders used for the height map.

I found a tool that can show the OpenGL and shading language version of your hardware here:
https://www.realtech-vr.com/home/glview

I hope this explains that weird looking error.
Best,
Rasmus

**Comment by KondakovArtem** [comment]
I also managed to build and compile the application for Linux Mint 19 and openframework 10. Apparently, they changed the work with kinect v1 in openframework 10. Everything works, but from time to time (every couple of seconds) the height map image is covered with noise, and it breaks the height lines. So I had to compile on ubuntu mate 14.04

**Comment by kreosz** [comment]
Thanks for the answers. The only option on these graphics cards. I tested on three computers, three graphics cards (but old, more then 7 year), two systems 7 and 10. I installed Direct, openGL, all Visual C ++, etc.  Still the same problems
0(29) : error C7532: global type sampler2DRect requires "#version 140" or later
0(29) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
0(46) : error C7531: global function texture2DRect requires "#extension GL_ARB_t
exture_rectangle : enable" before use

when i try shadersGL3... i have dark screen, but I can turn on the fish and rabbits.

**Comment by KondakovArtem** [comment]
What I did. I took a clean disk, installed Windows 7 64 bit, installed ms visual studio 2015, and what comes with it out of the box. The program worked for me on geforce 660 gtx, geforce 7200 gt (slow), rtx 2080, on AMD I did not try, because It was not at hand

**Comment by RasmusRPaulsen** [comment]
Okay.
It seems that this problem is related to the capabilities of the graphic card and also what version of the graphic card drivers you are using. If you have an older graphic card, try to install the latest drivers for it. If that is not helping, then a newer graphic card is probably the solution.

Technically, the shaders uses an OpenGL extension (GL_ARB_texture_rectangle) that requires a certain version of OpenGL to work. I found this list with known graphic cards that support that extension:

https://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_texture_rectangle

**Comment by kreosz** [comment]
Thank you very much for help.
I bought a used GeForce GTX 660 graphics card (MSI N660 TF 2GD5 / OC). After uploading the latest drivers. It started.
The children are happy!

Sławek

**Comment by marcelrv** [comment]
I'm struggling with the same. Grey screen.
However, the grapics card is reports GL_ARB_texture_rectangle.
Is there a way to find which other ones are requested?

**Comment by kreosz** [comment]
Hi
RasmusRPaulsen wrote above..

"Technically, the shaders uses an OpenGL extension (GL_ARB_texture_rectangle) that requires a certain version of OpenGL to work. I found this list with known graphic cards that support that extension:

[LINK](https://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_texture_rectangle)

...just check
